name: LeetCode Stats
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  leetcode:
    name: LeetCode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Update README
        env:
          LEETCODE_API_KEY: ${{ secrets.LEETCODE_API_KEY }}
        run: |
          python update_readme.py
